;; event dispatchers and related stuff ... 

(defclass dispatcher ()
  ((perform-dispatch)
   (handle-events)
   (handle-transition)))

;; simple time-recursive dispatching
(defmethod perform-dispatch ((d dispatcher) proc time &key)
  (when (and (gethash proc *processor-directory*) (is-active (gethash proc *processor-directory*)) )
    (handle-events d (pull-events (gethash proc *processor-directory*)))
    (let* ((trans-time (handle-transition d (car
					     (pull-transition
					      (gethash proc *processor-directory*)))))
	   (next (+ time #[trans-time ms])))
      (incudine:at next #'perform-dispatch d proc next))))

(defmethod handle-transition ((s dispatcher) (tr transition) &key)
  ;;(fresh-line)
  ;;(princ "the next events should happen in: ")
  ;;(princ (transition-duration tr))
  (transition-duration tr))	 

;; dummy dispatcher for testing and development
(defclass string-dispatcher (dispatcher) ())

(defmethod handle-events ((s string-dispatcher) events &key)
  (fresh-line)
  (princ "the following events should be handled: ")
  (mapc #'(lambda (event)
	    (princ (event-message event))
	    (princ " from ")
	    (princ (event-source event))
	    (princ ", ")) events))

;; the main event dispatcher
(defclass event-dispatcher (dispatcher) ())

(defmethod handle-events ((e event-dispatcher) events &key)
  (mapc #'handle-event events))

;; see what we can still do with this ... 
(defmethod handle-event ((e incomplete-event) &key))

;; if nothing else helps ...
(defmethod handle-event ((e event) &key))

;; handler methods for individual events ... 
(defmethod handle-event ((m midi-event) &key)
  (events (cm::new cm::midi
	       :time 0
	       :keynum (event-pitch m)
	       :duration (coerce (* (event-duration m) 0.001) 'single-float)
	       :amplitude (round (* 127 (event-level m))))
	  :at (incudine:now)))

(defmethod handle-event ((c control-event) &key)
  (funcall (control-function c)))

(defmethod handle-event ((g grain-event) &key)
  (if (member 'inc (event-backends g)) (handle-grain-event-incu g))
  (if (member 'sc (event-backends g)) (handle-grain-event-sc g)))

(defmethod handle-grain-event-sc ((g grain-event) &key)
  (unless (gethash (sample-location g) *buffer-directory*)
    (register-sample (sample-location g)))
  (let ((bufnum (gethash (sample-location g) *buffer-directory*)))
    (cm::send-osc  
     "/s_new"	    
     "siiisisfsfsfsfsfsfsfsfsfsfsfsfsfsfsf"
     "grain_2ch" -1 0 1
     "bufnum" bufnum
     "lvl" (coerce (event-level g) 'float)
     "rate" (coerce (rate g) 'float)
     "start" (coerce (start g) 'float)
     "lp_freq" (coerce (lp-freq g) 'float)
     "lp_q" (coerce (lp-q g) 'float)
     "lp_dist" (coerce (lp-dist g) 'float)
     "pf_freq" (coerce (pf-freq g) 'float)
     "pf_q" (coerce (pf-q g) 'float)
     "pf_gain" (coerce (pf-gain g) 'float)
     "hp_freq" (coerce (hp-freq g) 'float)
     "hp_q" (coerce (hp-q g)  'float)
     "a" (coerce (* (atk g) 0.001) 'float)
     "length" (coerce (* (- (event-duration g) (atk g) (rel g)) 0.001) 'float)
     "r" (coerce (* (rel g) 0.001) 'float)
     "pos" (coerce (- (event-position g) 0.5) 'float))))

(defmethod handle-grain-event-incu ((g grain-event) &key)
  (unless (gethash (sample-location g) *buffer-directory*)
    (let* ((buffer (incudine:buffer-load (sample-location g)))
	   (bdata (make-buffer-data :buffer buffer
				    :buffer-rate (/ (incudine:buffer-sample-rate buffer)
						    (incudine:buffer-frames buffer))
				    :buffer-frames (incudine:buffer-frames buffer))))
      (setf (gethash (sample-location g) *buffer-directory*) bdata)))
  (let ((bdata (gethash (sample-location g) *buffer-directory*)))    
    (cond ((and (not (event-ambi-p g)) (> (rev g) 0.0))
	   (scratch::megra-grain-rev (buffer-data-buffer bdata)
		 (buffer-data-buffer-rate bdata)
		 (buffer-data-buffer-frames bdata)
		 (event-level g)
		 (rate g)
		 (start g)
		 (lp-freq g)
		 (lp-q g)
		 (lp-dist g)
		 (pf-freq g)
		 (pf-q g)
		 (pf-gain g)
		 (hp-freq g)
		 (hp-q g)
		 (* (atk g) 0.001)
		 (* (- (event-duration g) (atk g) (rel g)) 0.001)
		 (* (rel g) 0.001)
		 (event-position g)
		 (rev g)
		 scratch::*rev-chapel*))
	((and (not (event-ambi-p g)) (<= (rev g) 0.0))  
	 (scratch::megra-grain (buffer-data-buffer bdata)
		 (buffer-data-buffer-rate bdata)
		 (buffer-data-buffer-frames bdata)
		 (event-level g)
		 (rate g)
		 (start g)
		 (lp-freq g)
		 (lp-q g)
		 (lp-dist g)
		 (pf-freq g)
		 (pf-q g)
		 (pf-gain g)
		 (hp-freq g)
		 (hp-q g)
		 (* (atk g) 0.001)
		 (* (- (event-duration g) (atk g) (rel g)) 0.001)
		 (* (rel g) 0.001)
		 (event-position g)
		 scratch::*rev-chapel*))
	((and (event-ambi-p g) (> (rev g) 0.0))  
	 (scratch::megra-grain-ambi-rev (buffer-data-buffer bdata)
		 (buffer-data-buffer-rate bdata)
		 (buffer-data-buffer-frames bdata)
		 (event-level g)
		 (rate g)
		 (start g)
		 (lp-freq g)
		 (lp-q g)
		 (lp-dist g)
		 (pf-freq g)
		 (pf-q g)
		 (pf-gain g)
		 (hp-freq g)
		 (hp-q g)
		 (* (atk g) 0.001)
		 (* (- (event-duration g) (atk g) (rel g)) 0.001)
		 (* (rel g) 0.001)
		 (event-azimuth g)
		 (event-elevation g)
		 (rev g)
		 scratch::*rev-chapel*))
	((and (event-ambi-p g) (<= (rev g) 0.0))  
	 (scratch::megra-grain-ambi (buffer-data-buffer bdata)
		 (buffer-data-buffer-rate bdata)
		 (buffer-data-buffer-frames bdata)
		 (event-level g)
		 (rate g)
		 (start g)
		 (lp-freq g)
		 (lp-q g)
		 (lp-dist g)
		 (pf-freq g)
		 (pf-q g)
		 (pf-gain g)
		 (hp-freq g)
		 (hp-q g)
		 (* (atk g) 0.001)
		 (* (- (event-duration g) (atk g) (rel g)) 0.001)
		 (* (rel g) 0.001)
		 (event-azimuth g)
		 (event-elevation g)
		 scratch::*rev-chapel*)))))
